<?php

namespace Database\Seeders;

use App\Models\Buyyer;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BuyyersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $buyers = [
            "Alby","Amber Interior","AREA DESIGN","ASK DESIGN","ATHOME","BALHANA","BALI","BALI PROJECT","BALICIOUS","BARBARA","BBB","BISTRO","BLANCH MARICLO","BLOCK & CHISEL","BLOOMINFVILLE","BOLTZE","BRICK BY BRICK","BROCKMEYER","BROMO","BTC","BUTLERS","BUTTERCUP","CAFE LIGHTING","CANAL LIVING","CATALOGUE 2021","CBC","CCST","CED","CHAKRA","CHAMI","CHR PLUSS","CALUDIA MONTE","COACHOUSE","COFUR","COSY MOBILER","CRANK FURNITURE","CTC","CULTURNITURE","DADACE","DEVO MEUBLES","DIVINO","DOVETAIL","DOWNEAST","EICHHOLTZ","ELAND","ERIC VAN BRUGEN","FINNDER FEBRIEK","FLAMANT","FLEXIBLE-BV","FLORABLLE","FLOREBELLE","FOURHANDS","FREDERIGI","GARPE","GERTSNEL","GLOBEWEST","GRUPE EDELWIESS","GULMOHARLANE","GUSJ","H&F","HAPPYNEST","HARRY THEHIRER","HK LIVING HOME","HOME AND SOUL","HOME DECO","HOME ESENTIAL","HOMEINVEST","HOSPITALITY","HOUSE & GARDEN","HUIQUIN","IMPORESIONEN","INGHOME","ISTANA FURNITURE","ITEM 2020","JUAN","JULIA","JULIA GROUP","KABAN LIVING","KERE DESIGN","KAVE HOME","KHEMCHAND","KIBU","L GUTMANN","KASSANDARI","LIFESTYLE","LINENHOUSE","LIVING KARMA","LIVINGSPACE","LOBERON","LOODS 5","LOUVRING","LULU & GEORGIA","MASION","MAJU HOME","MANUFAKTUR D","MARINA HOME","MARIOT ALMACENES","MARTINELI","MARTINENSEN","MASCOT ONLINE","MASTRO","MEADOWS & BYRNE","MEJA","MEUBLE ASIA","MGWB","MIHRAN","MILLO HOME","MONICA","MR.JAN","NAPA HOME","NOCHOLA HIGHS","NIKKY HOME","NINEGOLD","NS FURNITURE","NUNGU","OBETH","OCTOPUS","OKA","ONE WORLD","OT DEISGN","PHILDANSK","PILLOWTALK","PIN PORTUGAL","PLASTIK","PREMIERE HOUSEWARE","PRIMAS","PROLIVING","PROVINCIALHOMELIVING","PTMS","RANGKA","RAUXBROTHER","REALITYAVLABARI","RIVIERA MAISON","REBOERTMARK","ROOST","SAFAVIEH","SAMPARTNER","SANTANO","SARI ROTI","SEBRA","SELAMET","SHANGHAI DHASHI","SHANGHAI HAIZUO","SHANGHAI MACAW","SHANGHAI SHI GUANG LI","SHF","SIAMAKARATINDI","SIKA DESIGN","SIMLA","SLIGRO","SOFA 1","STYLE UP STAGING","SURYA","TERAIN","THDC","THE NICE FLEET","TORICELI","TOV","TRAZO DISENO","TRENDSFASION","TRIBE DUBAI","TRILOGY","TURKEY","TUSKER","UMA","UNITITLED","VALYOU","CANTHIL","VELVET","VENUS ET FLEUR","VERSMISSEN","VIDIO","WESTWING","WICKER EMPORIUM","WISTERIA","YARGICHI","ZARAHOME","ZUIVER"
        ];

        foreach ($buyers as $item) {
            Buyyer::create([
                'name'   => $item,
                'status' => '-'
            ]);
        }
    }
}
